### ISSUE TITLE
The X11 driver doesn't support external wiimote peripherals (i.e. classic controller and nunchuck)

### ISSUE THREAD

**Issue by danhansen** [xwiimote/xf86-input-xwiimote#3]
Looking at the source for the driver, I've noticed that the support for external wiimote peripherals exists, but the code in the X11 driver doesn't appear to implement any button mappings for them.

**Comment by dvdhrm** [comment]
Yes, that is true, but the xf86-input-xwiimote driver is only an example how this could be done. The recommended way to work with wiimotes is writing emulators via uinput. Feel free to send patches ;) However, it might take some time until I will get around writing the emulators as I am currently swamped with other work.

Regards
David

**Comment by danhansen** [comment]
I'm rather unfamiliar with uinput and the emulators you speak of. Any recommendations on where to learn more about it?

**Comment by dvdhrm** [comment]
I have written an example in the xwiimote repository in ./xwiimote/tools/xwiikeymap.c if you're interested.

**Comment by ShimmerFairy** [comment]
I've just stumbled into this myself I believe (where nothing, not even xwiishow, responds to the nunchuck or classic controller). Note that I'm using the supplied Xorg rules from both the xwiimote and xf86-input-xwiimote repositories.

The recommended `xwiimote/tools/xwiikeymap.c` no longer exists (the commit message for its removal states that "It's no longer maintained and it's recommended to use the xf86 or other drivers instead."), which is why I've bothered commenting on a closed bug report. Does this mean xf86-input-xwiimote will support things like the Nunchuck and classic controller in the future, or are there other existing drivers out there for those devices?

**Comment by dvdhrm** [comment]
If xwiishow does not show your nunchuck, then the nunchuck doesn't work. Are you sure you're using at least linux-3.12 and "xwiishow" correctly shows button presses?

**Comment by ShimmerFairy** [comment]
My mistake, I thought I had a new enough kernel (what with the ability to compile wiimote + extension support), I currently just have 3.10.25. I'll let you know if upgrading to the latest kernel, when I'm able to, doesn't fix the issue.

The kernel is probably the cause, seeing as two separate devices (one of which, the classic controller, is known to work) wouldn't be read.

EDIT: I just got kernel 3.13.2 and the classic controller is now recognized, so it was me not having a good enough kernel after all.
